apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  # deployment labels
  labels:
    purpose: blue-green
    project: roboshop
    app-track: {{ .Values.deployment.appTrack }}: blue
spec:
  replicas: 3
  # These are the labels replica set use to create pod replicas, this should match pod labels
  selector:
    matchLabels:
      purpose: blue-green
      project: roboshop
      app-track: {{ .Values.deployment.appTrack }}: blue
  # This is pod definition
  template:
    metadata:
      labels:
        purpose: blue-green
        project: roboshop
        app-track: {{ .Values.deployment.appTrack }}: {{ .Values.deployment.appTrack }}
    spec:
      containers:
      - name: nginx
        image: joindevops/nginx:{{ .Values.deployment.imageVersion }}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    purpose: service-demo
spec:
  selector:
    purpose: deployment-demo
    project: roboshop
    app: nginx
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port