apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  # deployment labels
  labels:
    purpose: blue-green
    project: roboshop
    app-track: {{ .Values.deployment.appTrack }}
spec:
  replicas: 3
  # These are the labels replica set use to create pod replicas, this should match pod labels
  selector:
    matchLabels:
      purpose: blue-green
      project: roboshop
      app-track: {{ .Values.deployment.appTrack }}
  # This is pod definition
  template:
    metadata:
      labels:
        purpose: blue-green
        project: roboshop
        app-track: {{ .Values.deployment.appTrack }}
    spec:
      containers:
      - name: nginx
        image: joindevops/nginx:{{ .Values.deployment.imageVersion }}